version: '3.8'
services:
 app:
  container_name: myrest
  image: myrestapi
  build: ./
  ports:
   - "8080:8080"
  depends_on:
   - mypostgres
  
 mypostgres:
  image: postgres
  ports:
   - "49156:5432"
  environment:
   - POSTGRES_PASSWORD=postgrespw
   - POSTGRES_USER=postgres
   - POSTGRES_DB=mydb
  volumes:
   - postgres:/data/postgres

volumes:
 postgres: